# -*- coding: utf-8 -*-
"""Laboratorio2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p0lqzHTwjJuunpHjvfsPGHvj_pG2NnXr
"""

import numpy as np 
import random
from matplotlib import pyplot as plt
import time


#Tomado de https://www.geeksforgeeks.org/insertion-sort/
def insertionSort(arr):  
    for i in range(1, len(arr)): 
        key = arr[i] 
        j = i-1
        while j >= 0 and key < arr[j] : 
                arr[j + 1] = arr[j] 
                j -= 1
        arr[j + 1] = key 

def arrAleatorio (n):
    arr=[0]*n
    for i in range (n):
        arr[i]=random.randint(0,800)
    return arr

for i in range (9^10):
    arr=arrAleatorio(i)
    T1=time.time()*1000
    insertionSort(arr)
    T2=time.time()*1000-T1
    area = np.pi*0.1
    colors = "green"
    plt.scatter(i, T1, s=area, c=colors, alpha=1)
    plt.title("Insertion Sort")

#Author: Juan Andres Giraldo. Camilo Cossio        
def InsertionSort(arr):
  for i in range (0, len(arr)):
    for j in range (i, len(arr)):
      if arr[i]>=arr[j]:
        temporal=arr[i]
        arr[i]=arr[j]
        arr[j]=temporal
  return arr
        
arr=[8, 4, 20, 5, 1]
print(InsertionSort(arr))

#Tomado de https://www.geeksforgeeks.org/merge-sort/
# Python program for implementation of MergeSort 
def mergeSort(arr): 
	if len(arr) >1: 
		mid = len(arr)//2  
		L = arr[:mid]  
		R = arr[mid:] 
		mergeSort(L) 
		mergeSort(R) 
		i = j = k = 0
		while i < len(L) and j < len(R): 
			if L[i] < R[j]: 
				arr[k] = L[i] 
				i+=1
			else: 
				arr[k] = R[j] 
				j+=1
			k+=1
		while i < len(L): 
			arr[k] = L[i] 
			i+=1
			k+=1
		while j < len(R): 
			arr[k] = R[j] 
			j+=1
			k+=1

# This code is contributed by Mayank Khanna 

for i in range (9^10):
    arr=arrAleatorio(i)
    T1=time.time()*1000
    insertionSort(arr)
    T2=time.time()*1000-T1
    area = np.pi*0.1
    colors = "red"
    plt.scatter(i, T1, s=area, c=colors, alpha=1)
    plt.title("Merge Sort")