# -*- coding: utf-8 -*-
"""Taller7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bVZ_ZqsXXBAg_rvKWHS6w6fIQ7HrirDv
"""

class nodo:
  def __init__(self, elDato):
    self.dato = elDato
    self.elSiguienteNodo = null
  
class ListaEnlazada:
  
  def __init__(self):
    self. elPrimerElementoDeLaLista = null
    self.size = 0
  
  def insertarAlPrincipio (e):
    temporal = nodo(e)
    temporal.elSiguienteNodo = elPrimerElementoDeLaLista
    self.elPrimerElementoDeLaLista = temporal
    self.size = size+1
  #complejidad O(1)
    
  def InsertarEnELSiguienteNVeces(nodo,n, dato):
    temporal = nodo(dato)
    respuesta = nodo
    for i in range(1,n-1):
      respuesta = respuesta.elSiguienteNodo
    respuesta.elSiguienteNodo = temporal
   #Complejidad O(n)
    
  def BorrarEnElSiguienteNVeces (n):
    respuesta = self.elPrimerElementoDeLaLista
    for i in range (1, n-1):
      respuesta = respuesta.elSiguienteNodo
    respuesta.elSiguienteNodo =  respuesta.elSiguienteNodo.elSiguienteNodo  
  #Complejidad O(n)
  
  def buscarCaracter (n):
    temporal = self.elPrimerElementoDeLaLista
    if temporal == n:
      return 0
    i = 1
    while temporal.elSiguienteNodo != null:
      if temporal.elSiguienteNodo == n:
        return i
      i = i+1
      temporal=temporal.elSiguienteNodo
    return -1
  
  def maximoValor(n):
    if ()