# -*- coding: utf-8 -*-
"""Laboratorio4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3nM03W1HtyXp1Ee6j5xYt9UddS1AsNK
"""

import urllib.request

url = 'https://raw.githubusercontent.com/mauriciotoro/ST0245-Eafit/master/laboratorios/lab04/DataSets/ejemplito.txt'
response = urllib.request.urlopen(url)
data = response.read()    
text = data.decode('utf-8')
arr = []
for i in range (0, len(text)):
  if(text[i] == ']'):
    aux = ""
    while (text[i]!='\n'):
      if(text[i] != ' ' and text[i] != ']'):
        aux += text[i]
      i+=1
    arr.append(aux)
print(arr)
print(text)

class Node:
  def __init__ (self, nombreArchivo = None, es_izq = False, es_der = False, es_raiz = False, padre = None):
    self.nombreArchivo = nombreArchivo
    self.izq = None
    self.der = None
    self.es_raiz = es_raiz
    self.es_der = es_der
    self.es_izq = es_izq
    self.padre = padre

class arbolBinario:
  def __init__ (self):
    self.raiz = None
    
  def agregar (self, nomArchivo):
    if self.raiz == None:
      self.raiz = Node(nombreArchivo = nomArchivo, es_raiz = True)
    else:
      nodo = self.obtenerLugar(nomArchivo)
      if nomArchivo[0] >= aux[0]:
        nodo.derecha = Nodo(nombreArchivo = nomArchivo, es_der = True, padre = nodo)
      else:
        nodo.izq = Nodo(nombreArchivo = nomArchivo, es_izq = True, padre = nodo)
  
  def obtenerLugar(self, nomArchivo):
    aux = self.raiz
    while aux != None:
      temporal = aux
      if nomArchivo[0] >= aux.nombreArchivo[0]:
        aux = aux.izq
      else:
        aux = aux.der
    return temporal
        
  def insertarArbol():
    for i in range (0, len(arr)):
      agregar(arr[i])