# -*- coding: utf-8 -*-
"""Laboratorio 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNiBmi0JK8R8KPsGGgk6ymkdPNBPthd8
"""

import urllib.request
import networkx as nx
import matplotlib as plt

url = 'https://raw.githubusercontent.com/ccossioa/ST0245-032/master/laboratorios/lab05/codigo/vertices.txt'
response = urllib.request.urlopen(url)
data = response.read()    
text = data.decode('utf-8')
arr = []
lista = []
for i in range (0, len(text)):
  if(text[i] == '\n'):
    aux = ""
    while i != len(text)-1 and text[i+1]!="\n" :
      aux += text[i]
      i+=1
    arr.append(aux)
for i in range(len(arr)-4):
  lista.append(arr[i].split())

url2 = 'https://raw.githubusercontent.com/ccossioa/ST0245-032/master/laboratorios/lab05/codigo/calles.txt'
response2 = urllib.request.urlopen(url2)
data2 = response2.read()    
text2 = data2.decode('utf-8')
arr2 = []
lista2 = []
for i in range (0, len(text2)):
  if(text2[i] == '\n'):
    aux2 = ""
    while i != len(text2)-1 and text2[i+1]!="\n" :
      aux2 += text2[i]
      i+=1
    arr2.append(aux2)
for i in range(len(arr2)):
  lista2.append(arr2[i].split())



G = nx.Graph()
for i in range (len(lista)):
  x = lista[i][3]
  G.add_node(x)
print("Nodos del grafo:")
print(G.nodes())

G = nx.Graph()
for i in range (len(lista2)):
  G.add_edge(lista2[i][0], lista2[i][1])
print("Calles del grafo:")
print(G.edges())

for i in range (len(lista)):
  print(lista[i][0], " = ", lista[i][3])

nx.draw_shell(G, with_labels=True, node_color = 'y')