# -*- coding: utf-8 -*-
"""taller6Punto2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ir4u_UChU0QU641NBsvPfQWLOGAcUUN0
"""

def scanner():
    arr = []
    num = int(input("Ingrese los numeros del arreglo, cuando quiera parar ingrese -1",))
    while num != -1:
        arr.append(num)
        num = int(input("Ingrese el siguente numero",))
    nuevo = []
    for i in range(0, len(arr)):
        nuevo[i] = arr[len(arr)-(i+1)]
    print(nuevo)