# -*- coding: utf-8 -*-
"""Taller6.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oaHfCl8YQfEfQRUt0zMVb-p4UZFykiZJ
"""

import numpy as np
class ArrayList:

    def __init__(self):
        self.elements = np.default(10);
        self.size = 0
        
        
    def size(self):
        return self.size
      
      
    def get(self, index):
        return self.elements [index]
      
      
    def add(self, object):
        if self.size == self.elements.size:
          nuevo = np.default(self.elements.size * 2)
          for i in range (0, elements.size):
            nuevo[i]=self.elements[i]
          self.elements = nuevo
        self.elements[size+1]=object
        self.size+=1
        
        
    def addInIndex(self, index, object):
        if index<=self.elements.size:
          nuevo = np.default(self.elements.size+1)
          for i in range (0, index):
            nuevo[i]=self.elements[i]
          nuevo[index]=object
          for j in range (index+1, self.elements.size):
            nuevo[j]=self.elements[j-1]
            self.elements=nuevo
            self.size+=1
        elif index==self.elements.size:
          nuevo = np.default(self.elements.size+1)
          for i in range (0, index):
            nuevo[i]= self.elements[i]
          nuevo[index]=object
          self.elements=nuevo
          self.size+=1
        else:
          print("No existe esa posicion en el arreglo")
          
    def deleteInIndex(self, index, object):
        if index<=self.elements.size:
          nuevo = np.default(self.elements.size-1)
          for i in range (0, index):
            nuevo[i]=self.elements[i]
          for j in range (index+1, self.elements.size):
            nuevo[j-1]=self.elements[j]
            self.elements=nuevo
            self.size-=1
        else:
          print("No existe esa posicion en el arreglo")

