# -*- coding: utf-8 -*-
"""Taller8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Up7CWJvhCrFf4nhL6vT3jHYEnHukCTjy
"""

diccionario = dict()
for i in range (0, 10):
   diccionario[input("Ahora ingrese el nombre de la persona ",)] = input("Ingrese el numero de celular ",)
def punto2 (dic, nombre):
  return dic[nombre]
punto1(diccionario, input("Ingrese el nombre de la persona ",))

empresas = dict()
for i in range (0, 10):
    empresas[input("Ahora ingrese la respectiva empresa ",)] = input("Ingrese el pais de la empresa ",)
def punto2 (dic, nombre):
  return dic[nombre]
punto1(empresa, input("Ingrese el nombre de la empresa que quiere buscar el pais ",))