# -*- coding: utf-8 -*-
"""Taller11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PAjDf-xqgYd9BDvHzL1GTJGpAbBpjh5
"""

import numpy as np

class GraphAm:

    def __init__(self, size):
      matriz = np.zeros(size,size)

    def getWeight(self, source, destination):
      return matriz[source][destination]

    def addArc(self, source, destination, weight):
      return matriz[source][destination] = weight

    def getSuccessors(self, vertex):
      arr = []
      for(i in range (0,size)):
        if matriz[vertex][i] != 0:
          arr.append(i)
      return arr
      
    def __str__(self):
      arr = [] 
      for i in range (0, size):
        for j in range(0, size):
          if matriz[i][j] != 0:
            arr.append('(',i,',',j,')')
    return arr